// Generated by gencpp from file common_msgs_pkg/encoder.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_PKG_MESSAGE_ENCODER_H
#define COMMON_MSGS_PKG_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_msgs_pkg
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : right_speed(0.0)
    , left_speed(0.0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : right_speed(0.0)
    , left_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _right_speed_type;
  _right_speed_type right_speed;

   typedef float _left_speed_type;
  _left_speed_type left_speed;





  typedef boost::shared_ptr< ::common_msgs_pkg::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs_pkg::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::common_msgs_pkg::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::common_msgs_pkg::encoder > encoderPtr;
typedef boost::shared_ptr< ::common_msgs_pkg::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs_pkg::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs_pkg::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs_pkg::encoder_<ContainerAllocator1> & lhs, const ::common_msgs_pkg::encoder_<ContainerAllocator2> & rhs)
{
  return lhs.right_speed == rhs.right_speed &&
    lhs.left_speed == rhs.left_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs_pkg::encoder_<ContainerAllocator1> & lhs, const ::common_msgs_pkg::encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs_pkg::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs_pkg::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs_pkg::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs_pkg::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs_pkg::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs_pkg::encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs_pkg::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25f978d6cccf487431c99e3026d97330";
  }

  static const char* value(const ::common_msgs_pkg::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25f978d6cccf4874ULL;
  static const uint64_t static_value2 = 0x31c99e3026d97330ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs_pkg::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs_pkg/encoder";
  }

  static const char* value(const ::common_msgs_pkg::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs_pkg::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 right_speed\n"
"float32 left_speed\n"
;
  }

  static const char* value(const ::common_msgs_pkg::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs_pkg::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right_speed);
      stream.next(m.left_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs_pkg::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs_pkg::encoder_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "right_speed: ";
    Printer<float>::stream(s, indent + "  ", v.right_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_speed: ";
    Printer<float>::stream(s, indent + "  ", v.left_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_PKG_MESSAGE_ENCODER_H
