// Generated by gencpp from file common_msgs_pkg/serial_data.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_PKG_MESSAGE_SERIAL_DATA_H
#define COMMON_MSGS_PKG_MESSAGE_SERIAL_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_msgs_pkg
{
template <class ContainerAllocator>
struct serial_data_
{
  typedef serial_data_<ContainerAllocator> Type;

  serial_data_()
    : PWM_Left(0)
    , PWM_Right(0)
    , command(0)
    , clear_encoder(false)  {
    }
  serial_data_(const ContainerAllocator& _alloc)
    : PWM_Left(0)
    , PWM_Right(0)
    , command(0)
    , clear_encoder(false)  {
  (void)_alloc;
    }



   typedef int8_t _PWM_Left_type;
  _PWM_Left_type PWM_Left;

   typedef int8_t _PWM_Right_type;
  _PWM_Right_type PWM_Right;

   typedef int8_t _command_type;
  _command_type command;

   typedef uint8_t _clear_encoder_type;
  _clear_encoder_type clear_encoder;





  typedef boost::shared_ptr< ::common_msgs_pkg::serial_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs_pkg::serial_data_<ContainerAllocator> const> ConstPtr;

}; // struct serial_data_

typedef ::common_msgs_pkg::serial_data_<std::allocator<void> > serial_data;

typedef boost::shared_ptr< ::common_msgs_pkg::serial_data > serial_dataPtr;
typedef boost::shared_ptr< ::common_msgs_pkg::serial_data const> serial_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs_pkg::serial_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs_pkg::serial_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs_pkg::serial_data_<ContainerAllocator1> & lhs, const ::common_msgs_pkg::serial_data_<ContainerAllocator2> & rhs)
{
  return lhs.PWM_Left == rhs.PWM_Left &&
    lhs.PWM_Right == rhs.PWM_Right &&
    lhs.command == rhs.command &&
    lhs.clear_encoder == rhs.clear_encoder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs_pkg::serial_data_<ContainerAllocator1> & lhs, const ::common_msgs_pkg::serial_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs_pkg::serial_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs_pkg::serial_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs_pkg::serial_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23aa005a44d993632cdb1134fc156a3a";
  }

  static const char* value(const ::common_msgs_pkg::serial_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23aa005a44d99363ULL;
  static const uint64_t static_value2 = 0x2cdb1134fc156a3aULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs_pkg/serial_data";
  }

  static const char* value(const ::common_msgs_pkg::serial_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 PWM_Left\n"
"int8 PWM_Right\n"
"int8 command\n"
"bool clear_encoder\n"
;
  }

  static const char* value(const ::common_msgs_pkg::serial_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PWM_Left);
      stream.next(m.PWM_Right);
      stream.next(m.command);
      stream.next(m.clear_encoder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs_pkg::serial_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs_pkg::serial_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "PWM_Left: ";
    Printer<int8_t>::stream(s, indent + "  ", v.PWM_Left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "PWM_Right: ";
    Printer<int8_t>::stream(s, indent + "  ", v.PWM_Right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "clear_encoder: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear_encoder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_PKG_MESSAGE_SERIAL_DATA_H
