# 基本参数
ekf_filter_node:
  frequency: 10.0           # 滤波频率(Hz)
  sensor_timeout: 0.2       # 传感器超时时间(s)
  two_d_mode: true         # 3D模式（若为地面机器人可设为true）

  # 坐标系设置
  publish_tf: true
  world_frame: odom          # 世界坐标系（固定）
  odom_frame: odom           # 里程计坐标系
  base_link_frame: base_link # 机器人基坐标系
  map_frame: map             # 地图坐标系（若不需要设为""）


  # 里程计数据配置（编码器）
  odom0: wheel_odom          # 编码器里程计话题
  odom0_config: [true,  true,  false,   # 使用x,y位置
                  false, false, true,    # 使用yaw角度
                  true,  false,  false,   # 使用vx线速度
                  false, false, true]    # 使用v_yaw角速度

  odom0_differential: false  # 非差分模式
  odom0_queue_size: 10       # 数据队列大小

  # IMU数据配置
  imu0: imu/data             # IMU话题
  imu0_config: [false, false, false,   # 不使用位置
                true,  true,  true,    # 使用yaw
                false, false, false,   # 不使用线速度
                true,  true,  true,    # 使用yaw角速度
                false,  false,  false]     # 不使用线加速度
  imu0_differential: true    # 差分模式（消除漂移）
  imu0_remove_gravitational_acceleration: true # 去除重力加速度
  odom0_queue_size: 10       # 数据队列大小

  # 过程噪声协方差（需根据传感器调整）
  process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]
  initial_estimate_covariance: [1e-3, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,
                                0,    1e-3, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,
                                0,    0,    1e-3, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,
                                0,    0,    0,    1e-3, 0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,
                                0,    0,    0,    0,    1e-3, 0,    0,    0,    0,    0,     0,     0,     0,     0,     0,
                                0,    0,    0,    0,    0,    1e-3, 0,    0,    0,    0,     0,     0,     0,     0,     0,
                                0,    0,    0,    0,    0,    0,    1e-3, 0,    0,    0,     0,     0,     0,     0,     0,
                                0,    0,    0,    0,    0,    0,    0,    1e-3, 0,    0,     0,     0,     0,     0,     0,
                                0,    0,    0,    0,    0,    0,    0,    0,    1e-3, 0,     0,     0,     0,     0,     0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-3,  0,     0,     0,     0,     0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,      1e-3,  0,     0,     0,     0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,      0,      1e-3,  0,     0,     0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,      0,      0,      1e-3,  0,     0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,      0,      0,      0,      1e-3,  0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,      0,      0,      0,      0,      1e-3]

                  