// Generated by gencpp from file decision_making_pkg/StartTransportRequest.msg
// DO NOT EDIT!


#ifndef DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORTREQUEST_H
#define DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision_making_pkg
{
template <class ContainerAllocator>
struct StartTransportRequest_
{
  typedef StartTransportRequest_<ContainerAllocator> Type;

  StartTransportRequest_()
    : placement_type(0)
    , placement_spacing(0.0)
    , start(false)  {
    }
  StartTransportRequest_(const ContainerAllocator& _alloc)
    : placement_type(0)
    , placement_spacing(0.0)
    , start(false)  {
  (void)_alloc;
    }



   typedef int8_t _placement_type_type;
  _placement_type_type placement_type;

   typedef float _placement_spacing_type;
  _placement_spacing_type placement_spacing;

   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartTransportRequest_

typedef ::decision_making_pkg::StartTransportRequest_<std::allocator<void> > StartTransportRequest;

typedef boost::shared_ptr< ::decision_making_pkg::StartTransportRequest > StartTransportRequestPtr;
typedef boost::shared_ptr< ::decision_making_pkg::StartTransportRequest const> StartTransportRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator1> & lhs, const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator2> & rhs)
{
  return lhs.placement_type == rhs.placement_type &&
    lhs.placement_spacing == rhs.placement_spacing &&
    lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator1> & lhs, const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace decision_making_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c75117dab7ae6528b49f68a745dce8d4";
  }

  static const char* value(const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc75117dab7ae6528ULL;
  static const uint64_t static_value2 = 0xb49f68a745dce8d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_making_pkg/StartTransportRequest";
  }

  static const char* value(const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求部分\n"
"int8 placement_type      # 0=网格摆放, 1=三角错位摆放\n"
"float32 placement_spacing # 摆放间距（米）\n"
"bool start               # 开始标志\n"
;
  }

  static const char* value(const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.placement_type);
      stream.next(m.placement_spacing);
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTransportRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_making_pkg::StartTransportRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_making_pkg::StartTransportRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "placement_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.placement_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "placement_spacing: ";
    Printer<float>::stream(s, indent + "  ", v.placement_spacing);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORTREQUEST_H
