// Generated by gencpp from file decision_making_pkg/StartTransportResponse.msg
// DO NOT EDIT!


#ifndef DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORTRESPONSE_H
#define DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision_making_pkg
{
template <class ContainerAllocator>
struct StartTransportResponse_
{
  typedef StartTransportResponse_<ContainerAllocator> Type;

  StartTransportResponse_()
    : success(false)
    , message()  {
    }
  StartTransportResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartTransportResponse_

typedef ::decision_making_pkg::StartTransportResponse_<std::allocator<void> > StartTransportResponse;

typedef boost::shared_ptr< ::decision_making_pkg::StartTransportResponse > StartTransportResponsePtr;
typedef boost::shared_ptr< ::decision_making_pkg::StartTransportResponse const> StartTransportResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator1> & lhs, const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator1> & lhs, const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace decision_making_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_making_pkg/StartTransportResponse";
  }

  static const char* value(const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应部分\n"
"bool success\n"
"string message\n"
;
  }

  static const char* value(const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTransportResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_making_pkg::StartTransportResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_making_pkg::StartTransportResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORTRESPONSE_H
