// Generated by gencpp from file decision_making_pkg/StartTransport.msg
// DO NOT EDIT!


#ifndef DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORT_H
#define DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORT_H

#include <ros/service_traits.h>


#include <decision_making_pkg/StartTransportRequest.h>
#include <decision_making_pkg/StartTransportResponse.h>


namespace decision_making_pkg
{

struct StartTransport
{

typedef StartTransportRequest Request;
typedef StartTransportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTransport
} // namespace decision_making_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::decision_making_pkg::StartTransport > {
  static const char* value()
  {
    return "a29e616be9ef3884c858e9b72ec65988";
  }

  static const char* value(const ::decision_making_pkg::StartTransport&) { return value(); }
};

template<>
struct DataType< ::decision_making_pkg::StartTransport > {
  static const char* value()
  {
    return "decision_making_pkg/StartTransport";
  }

  static const char* value(const ::decision_making_pkg::StartTransport&) { return value(); }
};


// service_traits::MD5Sum< ::decision_making_pkg::StartTransportRequest> should match
// service_traits::MD5Sum< ::decision_making_pkg::StartTransport >
template<>
struct MD5Sum< ::decision_making_pkg::StartTransportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::decision_making_pkg::StartTransport >::value();
  }
  static const char* value(const ::decision_making_pkg::StartTransportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::decision_making_pkg::StartTransportRequest> should match
// service_traits::DataType< ::decision_making_pkg::StartTransport >
template<>
struct DataType< ::decision_making_pkg::StartTransportRequest>
{
  static const char* value()
  {
    return DataType< ::decision_making_pkg::StartTransport >::value();
  }
  static const char* value(const ::decision_making_pkg::StartTransportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::decision_making_pkg::StartTransportResponse> should match
// service_traits::MD5Sum< ::decision_making_pkg::StartTransport >
template<>
struct MD5Sum< ::decision_making_pkg::StartTransportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::decision_making_pkg::StartTransport >::value();
  }
  static const char* value(const ::decision_making_pkg::StartTransportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::decision_making_pkg::StartTransportResponse> should match
// service_traits::DataType< ::decision_making_pkg::StartTransport >
template<>
struct DataType< ::decision_making_pkg::StartTransportResponse>
{
  static const char* value()
  {
    return DataType< ::decision_making_pkg::StartTransport >::value();
  }
  static const char* value(const ::decision_making_pkg::StartTransportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DECISION_MAKING_PKG_MESSAGE_STARTTRANSPORT_H
