// Generated by gencpp from file serial_stm32_pkg/EncoderData.msg
// DO NOT EDIT!


#ifndef SERIAL_STM32_PKG_MESSAGE_ENCODERDATA_H
#define SERIAL_STM32_PKG_MESSAGE_ENCODERDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_stm32_pkg
{
template <class ContainerAllocator>
struct EncoderData_
{
  typedef EncoderData_<ContainerAllocator> Type;

  EncoderData_()
    : Encoder_Left(0)
    , Encoder_Right(0)  {
    }
  EncoderData_(const ContainerAllocator& _alloc)
    : Encoder_Left(0)
    , Encoder_Right(0)  {
  (void)_alloc;
    }



   typedef uint32_t _Encoder_Left_type;
  _Encoder_Left_type Encoder_Left;

   typedef uint32_t _Encoder_Right_type;
  _Encoder_Right_type Encoder_Right;





  typedef boost::shared_ptr< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderData_

typedef ::serial_stm32_pkg::EncoderData_<std::allocator<void> > EncoderData;

typedef boost::shared_ptr< ::serial_stm32_pkg::EncoderData > EncoderDataPtr;
typedef boost::shared_ptr< ::serial_stm32_pkg::EncoderData const> EncoderDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_stm32_pkg::EncoderData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_stm32_pkg::EncoderData_<ContainerAllocator1> & lhs, const ::serial_stm32_pkg::EncoderData_<ContainerAllocator2> & rhs)
{
  return lhs.Encoder_Left == rhs.Encoder_Left &&
    lhs.Encoder_Right == rhs.Encoder_Right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_stm32_pkg::EncoderData_<ContainerAllocator1> & lhs, const ::serial_stm32_pkg::EncoderData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_stm32_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f445708b5fc7868c7f94d572914b055";
  }

  static const char* value(const ::serial_stm32_pkg::EncoderData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f445708b5fc7868ULL;
  static const uint64_t static_value2 = 0xc7f94d572914b055ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_stm32_pkg/EncoderData";
  }

  static const char* value(const ::serial_stm32_pkg::EncoderData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 Encoder_Left\n"
"uint32 Encoder_Right\n"
;
  }

  static const char* value(const ::serial_stm32_pkg::EncoderData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Encoder_Left);
      stream.next(m.Encoder_Right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_stm32_pkg::EncoderData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_stm32_pkg::EncoderData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Encoder_Left: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Encoder_Left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Encoder_Right: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.Encoder_Right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_STM32_PKG_MESSAGE_ENCODERDATA_H
