// Generated by gencpp from file tracking_pkg/track.msg
// DO NOT EDIT!


#ifndef TRACKING_PKG_MESSAGE_TRACK_H
#define TRACKING_PKG_MESSAGE_TRACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tracking_pkg
{
template <class ContainerAllocator>
struct track_
{
  typedef track_<ContainerAllocator> Type;

  track_()
    : line()  {
      line.assign(0);
  }
  track_(const ContainerAllocator& _alloc)
    : line()  {
  (void)_alloc;
      line.assign(0);
  }



   typedef boost::array<int16_t, 4>  _line_type;
  _line_type line;





  typedef boost::shared_ptr< ::tracking_pkg::track_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracking_pkg::track_<ContainerAllocator> const> ConstPtr;

}; // struct track_

typedef ::tracking_pkg::track_<std::allocator<void> > track;

typedef boost::shared_ptr< ::tracking_pkg::track > trackPtr;
typedef boost::shared_ptr< ::tracking_pkg::track const> trackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracking_pkg::track_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracking_pkg::track_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tracking_pkg::track_<ContainerAllocator1> & lhs, const ::tracking_pkg::track_<ContainerAllocator2> & rhs)
{
  return lhs.line == rhs.line;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tracking_pkg::track_<ContainerAllocator1> & lhs, const ::tracking_pkg::track_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tracking_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tracking_pkg::track_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracking_pkg::track_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_pkg::track_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_pkg::track_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_pkg::track_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_pkg::track_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracking_pkg::track_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d30351f4c1b67d57e1e20725088b7c6";
  }

  static const char* value(const ::tracking_pkg::track_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d30351f4c1b67d5ULL;
  static const uint64_t static_value2 = 0x7e1e20725088b7c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::tracking_pkg::track_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracking_pkg/track";
  }

  static const char* value(const ::tracking_pkg::track_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracking_pkg::track_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[4] line\n"
;
  }

  static const char* value(const ::tracking_pkg::track_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracking_pkg::track_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct track_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracking_pkg::track_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracking_pkg::track_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "line: ";
    if (v.line.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.line.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int16_t>::stream(s, true ? std::string() : indent + "    ", v.line[i]);
    }
    if (v.line.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKING_PKG_MESSAGE_TRACK_H
