// Generated by gencpp from file processdata_pkg/serial_data.msg
// DO NOT EDIT!


#ifndef PROCESSDATA_PKG_MESSAGE_SERIAL_DATA_H
#define PROCESSDATA_PKG_MESSAGE_SERIAL_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace processdata_pkg
{
template <class ContainerAllocator>
struct serial_data_
{
  typedef serial_data_<ContainerAllocator> Type;

  serial_data_()
    : PWM_Left(0)
    , PWM_Right(0)
    , command(0)  {
    }
  serial_data_(const ContainerAllocator& _alloc)
    : PWM_Left(0)
    , PWM_Right(0)
    , command(0)  {
  (void)_alloc;
    }



   typedef int8_t _PWM_Left_type;
  _PWM_Left_type PWM_Left;

   typedef int8_t _PWM_Right_type;
  _PWM_Right_type PWM_Right;

   typedef int8_t _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::processdata_pkg::serial_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::processdata_pkg::serial_data_<ContainerAllocator> const> ConstPtr;

}; // struct serial_data_

typedef ::processdata_pkg::serial_data_<std::allocator<void> > serial_data;

typedef boost::shared_ptr< ::processdata_pkg::serial_data > serial_dataPtr;
typedef boost::shared_ptr< ::processdata_pkg::serial_data const> serial_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::processdata_pkg::serial_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::processdata_pkg::serial_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::processdata_pkg::serial_data_<ContainerAllocator1> & lhs, const ::processdata_pkg::serial_data_<ContainerAllocator2> & rhs)
{
  return lhs.PWM_Left == rhs.PWM_Left &&
    lhs.PWM_Right == rhs.PWM_Right &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::processdata_pkg::serial_data_<ContainerAllocator1> & lhs, const ::processdata_pkg::serial_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace processdata_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::processdata_pkg::serial_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::processdata_pkg::serial_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::processdata_pkg::serial_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::processdata_pkg::serial_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::processdata_pkg::serial_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::processdata_pkg::serial_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::processdata_pkg::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55d8902ce6b1a26e186815e49dac35e0";
  }

  static const char* value(const ::processdata_pkg::serial_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55d8902ce6b1a26eULL;
  static const uint64_t static_value2 = 0x186815e49dac35e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::processdata_pkg::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "processdata_pkg/serial_data";
  }

  static const char* value(const ::processdata_pkg::serial_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::processdata_pkg::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 PWM_Left\n"
"int8 PWM_Right\n"
"int8 command\n"
;
  }

  static const char* value(const ::processdata_pkg::serial_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::processdata_pkg::serial_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PWM_Left);
      stream.next(m.PWM_Right);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::processdata_pkg::serial_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::processdata_pkg::serial_data_<ContainerAllocator>& v)
  {
    s << indent << "PWM_Left: ";
    Printer<int8_t>::stream(s, indent + "  ", v.PWM_Left);
    s << indent << "PWM_Right: ";
    Printer<int8_t>::stream(s, indent + "  ", v.PWM_Right);
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROCESSDATA_PKG_MESSAGE_SERIAL_DATA_H
